// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKA31tEOGUyAE1kuWXeuGXJXpe6wsV-XE',
    appId: '1:986160956195:web:ae4b391579ec2a22a58296',
    messagingSenderId: '986160956195',
    projectId: 'afyaexpress-8992e',
    authDomain: 'afyaexpress-8992e.firebaseapp.com',
    storageBucket: 'afyaexpress-8992e.appspot.com',
    measurementId: 'G-ENQ1RN0FJ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkigpM8HdEhtIBU3IB3belZCmotI0pl-I',
    appId: '1:986160956195:android:6f247e0eb20bd24ea58296',
    messagingSenderId: '986160956195',
    projectId: 'afyaexpress-8992e',
    storageBucket: 'afyaexpress-8992e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDcaN3cqgQyiI6y3wrRJdm6ScVud_CJRo',
    appId: '1:986160956195:ios:cdf80455210116c2a58296',
    messagingSenderId: '986160956195',
    projectId: 'afyaexpress-8992e',
    storageBucket: 'afyaexpress-8992e.appspot.com',
    iosBundleId: 'com.expresske.afyaexpress',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDcaN3cqgQyiI6y3wrRJdm6ScVud_CJRo',
    appId: '1:986160956195:ios:cdf80455210116c2a58296',
    messagingSenderId: '986160956195',
    projectId: 'afyaexpress-8992e',
    storageBucket: 'afyaexpress-8992e.appspot.com',
    iosBundleId: 'com.expresske.afyaexpress',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKA31tEOGUyAE1kuWXeuGXJXpe6wsV-XE',
    appId: '1:986160956195:web:971f70736458991fa58296',
    messagingSenderId: '986160956195',
    projectId: 'afyaexpress-8992e',
    authDomain: 'afyaexpress-8992e.firebaseapp.com',
    storageBucket: 'afyaexpress-8992e.appspot.com',
    measurementId: 'G-7KCP0GJWVR',
  );
}
